export { analyzeContextBombs } from './context-bombs';
export { analyzeDeadWeight } from './dead-weight';
export type { DeadWeightOptions } from './dead-weight';
export { analyzeCoupling } from './coupling';
export { analyzeReexportEntropy } from './reexport-entropy';
export { analyzeDuplication } from './duplication';
export type { DuplicationOptions } from './duplication';
export { analyzeUnusedImports } from './unused-imports';
export type { UnusedImportsOptions } from './unused-imports';
export { runHeuristics } from './run-heuristics';
export type { PluginHeuristicOptions, HeuristicsResult } from './run-heuristics';
